- name: Create Instance
  hosts: local
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        name: iad.docker.%03d
        count: 1
        exact_count: yes
        key_name: ansible_demo
        flavor: performance1-1 
        image: 5cc098a5-7286-4b96-b3a2-49f4c4f82537
        wait: yes
        group: docker
        state: present
      register: raxtest
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.accessIPv4 }} groupname=docker
      with_items: raxtest.instances
- name: Install Docker
  hosts: docker
  user: root
  tasks:
    - name: Update cache
      shell: apt-get update
    - name: Install docker.io package via apt-get
      shell: apt-get -y install docker.io
    - name: Link docker to /usr/bin/docker.io 
      shell: ln -sf /usr/bin/docker.io /usr/local/bin/docker
    - name: Update bashe completion 
      shell: sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io

