- name: Build Mongo Servers in Rax Cloud
  hosts: local
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        name: mongo%01d
        count: 3
        exact_count: yes
        key_name: ansible_demo
        flavor: performance1-1 
        image: f70ed7c7-b42e-4d77-83d8-40fa29825b85
        wait: yes
        group: replication_servers
        state: present
      register: rax
    - name: Add Mongo Servers to replications_servers
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        groupname: replication_servers
      with_items: rax.success
      when: rax.action == 'create'
    - name: Find master server
      local_action:
        module: add_host
        hostname: "{{ item.1 }}"
        groupname: master_servers
      with_indexed_items: groups.replication_servers
      when: item.0 == 0
- name: Install Mongodb packages
  hosts: replication_servers
  gather_facts: True
  roles:
   - role: common
- name: Setup Mongodb Replicaset members
  hosts: replication_servers
  gather_facts: True
  roles:
   - role: mongod
- name: Intialize Mongodb Replicasets
  hosts: master_servers
  gather_facts: True
  tasks:
   - include: roles/mongod/tasks/master.yml

